# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: ubuntu
  become: true

  roles:
    - server_config
    - ansible-role-ntp 
