# Molecule managed

---
dependency:
  command: null
  enabled: true
  env: {}
  name: galaxy
  options: {}
driver:
  name: docker
  options:
    managed: true
  provider:
    name: null
  safe_files: []
  ssh_connection_options: []
platforms:
  - command: ''
    image: geerlingguy/docker-centos7-ansible:latest
    name: instance
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
prerun: true
provisioner:
  ansible_args: []
  children: {}
  config_options: {}
  connection_options: {}
  env: {}
  inventory:
    group_vars: {}
    host_vars: {}
    hosts: {}
    links: {}
  log: true
  name: ansible
  options: {}
  playbooks:
    cleanup: cleanup.yml
    converge: converge.yml
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml
    side_effect: side_effect.yml
    verify: verify.yml
scenario:
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - cleanup
    - destroy
  cleanup_sequence:
    - cleanup
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  create_sequence:
    - dependency
    - create
    - prepare
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  name: default
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  additional_files_or_dirs: []
  enabled: true
  env: {}
  name: ansible
  options: {}
